### ISSUE TITLE
C version?

### ISSUE THREAD

**Issue by OJFord** [m8pple/langproc_2014_cw#2]
Which version of C is to be compiled?

I thought that it was stated (before coursework 'start date'/release) that it would be C89 - in the context of, I think, "so you won't have to worry about mid-scope declarations for this coursework".

But spec.md doesn't mention specifically, and at least some of the sample test inputs use C++/C99 'end of line' comments.

**Comment by m8pple** [comment]
A good point.

I will tighten it to be only C89.

You're right that I'm not particularly compliant on the pre-processor style - I've modified them all
to be c-style comments, though obviously it doesn't make too much difference in what your compilers
see.

**Comment by m8pple** [comment]
(Forgot to close via commit message).
